#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"

# 処理開始時刻を保存
processing_time.start "${stfw_process_dir:?}"
retcode=$?

stfw.webhook.async_execute process start "${stfw_process_dir:?}" "process/${stfw_process:?}" >/dev/null

exit $retcode
