#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"

webhook.createhook "${run_id:?}" run end

# 処理時間を表示
processing_time=$(processing_time.calc "${run_id:?}")
(
  echo "result:"
  echo "  run:"
  echo "    id: ${run_id:?}"
  echo "    processing_time: ${processing_time}"
) | log.info

exit ${EXITCODE_SUCCESS}
