language: ruby
rvm:
  - 2.3.3
env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.1
install:
  - wget $URL/redpen-1.10.1.tar.gz
  - tar xvf redpen-1.10.1.tar.gz
  - export PATH=$PATH:$PWD/redpen-distribution-1.10.1/bin
  - gem install asciidoctor
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - sudo pip install pyaml
  - sudo pip install docopt
script:
  - ./build/docs/build.sh
  - ./build/product/build.sh
