#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"

# 処理開始時刻を保存
processing_time.start "${stfw_bizdate_dir:?}"
retcode=$?

stfw.webhook.async_execute bizdate start "${stfw_bizdate_dir:?}" >/dev/null

exit $retcode
