#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"

# 処理開始時刻を保存
processing_time.start "${stfw_scenario_dir:?}"
retcode=$?

stfw.webhook.async_execute "${stfw_scenario_dir:?}" scenario start

exit $retcode
