#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"
. "${DIR_BIN_LIB}/stfw/adapter/cli/webhook_controller"

# 処理開始時刻を保存
processing_time.start "${stfw_scenario_dir:?}"

stfw.adapter.cli.webhook.scenario_start "${stfw_scenario_dir:?}"
exit $?
