stfw:
  # digdag
  server:
    # バインドホスト
    bind: "0.0.0.0"
    # ポート
    port: 3000
    # DBモード --memory | --database /path/to/db_dir
    db_mode: "--memory"
    # taskスレッド上限
    max_task_threads: 64
    # timezone
    timezone: "Asia/Tokyo"

  # ログレベル trace | debug | info | warn | error
  loglevel: "info"

  # sample
  list_sample:
  - list_value1
  - list_value2
