#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"

webhook.async_execute "${stfw_scenario_dir:?}" scenario end

# 処理時間を表示
processing_time=$(processing_time.calc "${stfw_scenario_dir:?}")
(
  echo "result:"
  echo "  run:"
  echo "    id: ${run_id:?}"
  echo "    scenario:"
  echo "      name: $(basename ${stfw_scenario_dir:?})"
  echo "      processing_time: ${processing_time}"
) | log.info

exit ${EXITCODE_SUCCESS}
