#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"

stfw.webhook.async_execute scenario end "${stfw_scenario_dir:?}"                                   |
grep                                                                                               \
  -e "^payload:"                                                                                   \
  -e "^  id:"                                                                                      \
  -e "^  type:"                                                                                    \
  -e "^  status:"                                                                                  \
  -e "^  start_time:"                                                                              \
  -e "^  end_time:"                                                                                \
  -e "^  processing_time:"                                                                         |
sed -e 's|^payload:|result:|'                                                                      |
log.info

exit ${EXITCODE_SUCCESS}
