#!/bin/bash
. "${STFW_HOME:?}/bin/lib/setenv"
. "${DIR_BIN_LIB:?}/logging_utils"

# 処理時間を表示
processing_time=$(log.processing_time.calc "${stfw_bizdate_dir:?}")
(
  echo "result:"
  echo "  run:"
  echo "    id: ${run_id:?}"
  echo "    scenario:"
  echo "      name: $(basename ${stfw_scenario_dir:?})"
  echo "      bizdate:"
  echo "        seq: ${stfw_bizdate_seq:?}"
  echo "        date: ${stfw_bizdate:?}"
  echo "        processing_time: ${processing_time}"
) | log.info

exit ${EXITCODE_SUCCESS}
